baseurl = "https://hajsong.github.io/"
disable404 = true
disableRSS = true
disableSitemap = true
googleAnalytics = "UA-110544334-1"
languageCode = "en-us"
theme = "hugo-orbit-theme"
title = "Hajoon Song"
[params]
author = "Pavel Kanyshev"
description = "Hugo Responsive Resume/CV Theme for Developers"
styles = "styles-6.css"
[params.contact]
enable = true
[[params.contact.list]]
class = "email"
icon = "fa-envelope"
title = "hajsong@yonsei.ac.kr"
url = "mailto: hajsong@yonsei.ac.kr"
[[params.contact.list]]
class = "phone"
icon = "fa-phone"
title = "+82-2-2123-257"
url = "tel:+82-2-2123-2579"
[[params.contact.list]]
class = "website"
icon = "fa-globe"
title = "hajsong.github.io"
url = "//hajsong.github.io"
[[params.contact.list]]
class = "github"
icon = "fa-github"
title = "github.com/hajsong"
url = "//github.com/hajsong"
[params.education]
enable = true
title = "Education"
[[params.education.list]]
college = "University of Caifornia, San Diego"
dates = "2005 - 2011"
degree = "Ph.D. in Earth Sciences"
[[params.education.list]]
college = "Yonsei University"
dates = "1999 - 2005"
degree = "BSc in Atmospheric Sciences"
[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Experiences"
[params.footer]
copyright = "Hajoon Song"
[params.interests]
enable = true
title = "Research Interests"
[[params.interests.list]]
interest = "Ocean/Atmosphere modeling"
[[params.interests.list]]
interest = "Air-sea interaction"
[[params.interests.list]]
interest = "Carbon cycle"
[[params.interests.list]]
interest = "Data assimilation"
[[params.jobs.list]]
company = "Department of Atmospheric Sciences, Yonsei University, Seoul, Korea"
dates = "2018 - Present"
details = "Principle Investigator at <a href=http://airsea.yonsei.ac.kr/>Air-sea Modeling Laboratory</a>"
position = "Assistant Professor"
[[params.jobs.list]]
company = "Department of Earth, Atmospheric and Planetary Sciences, MIT, Cambridge, USA"
dates = "2013 - 2018"
details = "The mesoscale circulation in the Southern Ocean and biogeochemistry"
position = "Research Scientist / Postdoctoral Associate"
[[params.jobs.list]]
company = "Ocean Sciences Department, UC, Santa Cruz, USA"
dates = "2011 - 2013"
details = "Development of the data assilimation method for biogeochemical variables"
position = "Postdoctoral Researcher"
[params.language]
enable = false
title = "Languages"
[[params.language.list]]
language = "English"
level = "Native"
[[params.language.list]]
language = "French"
level = "Professional"
[[params.language.list]]
language = "Russian"
level = "Professional"
[params.profile]
avatar = "HajoonSong.png"
name = "Hajoon Song"
tagline = "Scientist / Professor"
[params.projects]
enable = true
icon = "fa-book"
intro = "**Peer-reviewed publication since 2016**."
title = "Publication"
[[params.projects.list]]
tagline = "Eddy compensation dampens Southern Ocean SST response to westerly wind trends. _Geophys. Res. Lett._, accepted"
title = "Doddridge, E. W., J. Marshall, H. Song, M. Kelley and L. Nazarenko"
url = "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2019GL082758"
[[params.projects.list]]
tagline = "CCE II: Spatial and interannual variability in export efficiency and the biological pump in an eastern boundary current upwelling system with substantial lateral advection. _Deep-Sea Res. Pt I_, 140, 14-25"
title = "Kelly, T, R. Goericke, M. Kahru, H. Song and M. R. Stukel (2018)"
url = "https://www.researchgate.net/publication/327098710_CCE_II_Spatial_and_interannual_variability_in_export_efficiency_and_the_biological_pump_in_an_eastern_boundary_current_upwelling_system_with_substantial_lateral_advection"
[[params.projects.list]]
tagline = "Seasonal variation in the correlation between anomalies of sea level and chlorophyll in the Antarctic Circumpolar Current region. _Geophys. Res. Lett._, 45, 5011-5019"
title = "Song, H., M. C. Long, P. Gaube, I. Frenger, J. Marshall and D. J. McGillicuddy Jr. (2018)"
url = "https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2017GL076246"
[[params.projects.list]]
tagline = "The role of subduction and gravitational sinking in particle export, carbon sequestration, and the remineralization length scale in the California Current Ecosystem. _Limnol. Oceanogr._, 63, 363–383"
title = "Stukel, M. R., H. Song, R. Goericke, A. J. Miller (2017)"
url = "https://aslopubs.onlinelibrary.wiley.com/doi/full/10.1002/lno.10636"
[[params.projects.list]]
tagline = "Deepwater mesoscale fronts enhance export in the California Current Ecosystem. _PNAS_, 114, 1252-1257"
title = "Stukel, M. R., L. I. Aluwihare, K. A. Barbeau, A. M. Chekalyuk, R. Goericke, A. J. Miller, M. D. Ohman, A. Ruacho, H. Song, B. Stephens and M. R. Landry (2017)"
url = "https://www.pnas.org/content/early/2017/01/19/1609435114.short"
[[params.projects.list]]
tagline = "Data assimilation of physical and chlorophyll observations in the California Current System using two biogeochemical models. _Ocean Model._, 109, 55-71"
title = "Mattern, J. P., H. Song, C. A. Edward, A. M. Moore and J. Fiechter (2017)"
url = "https://www.sciencedirect.com/science/article/pii/S1463500316301470"
[[params.projects.list]]
tagline = "Mesoscale modulation of air-sea CO<sub>2</sub> flux in Drake Passage. _J. Geophys. Res. Oceans._, 121, 6635-6649"
title = "Song, H., J. Marshall, D. R. Munro, S. Dutkiewicz, C. Sweeney, D. J. McGillicuddy Jr. and U. Hausmann (2016)"
url = "https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2016JC011714"
[[params.projects.list]]
tagline = "Data assimilation in a coupled physicalbiogeochemical model of the California Current System using an incremental lognormal 4-dimensional variational approach: Part 1, Model formulation and biological data assimilation twin experiments. _Ocean Model._, 106, 131-145"
title = "Song, H., C. A. Edwards, A. M. Moore and J. Fietcher (2016)"
url = "https://www.sciencedirect.com/science/article/pii/S1463500316300063"
[[params.projects.list]]
tagline = "Data assimilation in a coupled physicalbiogeochemical model of the California Current System using an incremental lognormal 4-dimensional variational approach: Part 2, Joint physical and biological data assimilation twin experiments. _Ocean Model._, 106, 146-158"
title = "Song, H., C. A. Edwards, A. M. Moore and J. Fietcher (2016)"
url = "https://www.sciencedirect.com/science/article/pii/S1463500316300919"
[[params.projects.list]]
tagline = "Data assimilation in a coupled physicalbiogeochemical model of the California Current System using an incremental lognormal 4-dimensional variational approach: Part 3, Assimilation in a realistic context using satellite and in situ observations. _Ocean Model._, 106, 159-172"
title = "Song, H., C. A. Edwards, A. M. Moore and J. Fietcher (2016)"
url = "https://www.sciencedirect.com/science/article/pii/S1463500316300555"
[[params.projects.list]]
tagline = "Source waters for the highly productive Patagonian shelf in the southwestern Atlantic. _J. Mar. Syst._, 158, 120-128"
title = "Song, H., J. Marshall, M. J. Follows, S. Dutkiewicz and G. Forget (2016)"
url = "https://www.sciencedirect.com/science/article/pii/S0924796316000452"
[params.skills]
enable = false
icon = "fa-rocket"
title = "Skills & Proficiency"
[[params.skills.list]]
level = "98%"
skill = "Python & Django"
[[params.skills.list]]
level = "98%"
skill = "Javascript & jQuery"
[[params.skills.list]]
level = "95%"
skill = "Angular"
[[params.skills.list]]
level = "95%"
skill = "HTML5 & CSS"
[[params.skills.list]]
level = "75%"
skill = "Ruby on Rails"
[[params.skills.list]]
level = "60%"
skill = "Sketch & Photoshop"
[params.summary]
enable = true
icon = "fa-user"
summary = "I am a scientist seeking to improve our understanding of the **interactions between air and sea, and their control on the carbon cycle in both global and regional scales.** Most of my research uses varied types of numerical simulations; from the 40-variable Lorenz-96 model to the state-of-art ocean circulation models such as MITgcm and ROMS, from forward time-stepping simulations to backward time-stepping adjoint sensitivity and data assimilation runs, and from physical ocean circulation model to that coupled with biogeochemical models."
title = "Short Bio"
